// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQux_aMhUfrBdXY545yKBVxFqbaQqa7i8',
    appId: '1:885029793401:web:4f745295990259291f6ea8',
    messagingSenderId: '885029793401',
    projectId: 'tecnigo-6c76c',
    authDomain: 'tecnigo-6c76c.firebaseapp.com',
    storageBucket: 'tecnigo-6c76c.firebasestorage.app',
    measurementId: 'G-6M4SQ9Y6JM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOj_j6o0j36sgzJy1S63mhDIXwCVOtvDo',
    appId: '1:885029793401:ios:f8f521106b2dee041f6ea8',
    messagingSenderId: '885029793401',
    projectId: 'tecnigo-6c76c',
    storageBucket: 'tecnigo-6c76c.firebasestorage.app',
    iosBundleId: 'com.example.tecnigo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOj_j6o0j36sgzJy1S63mhDIXwCVOtvDo',
    appId: '1:885029793401:ios:f8f521106b2dee041f6ea8',
    messagingSenderId: '885029793401',
    projectId: 'tecnigo-6c76c',
    storageBucket: 'tecnigo-6c76c.firebasestorage.app',
    iosBundleId: 'com.example.tecnigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQux_aMhUfrBdXY545yKBVxFqbaQqa7i8',
    appId: '1:885029793401:web:4f745295990259291f6ea8',
    messagingSenderId: '885029793401',
    projectId: 'tecnigo-6c76c',
    authDomain: 'tecnigo-6c76c.firebaseapp.com',
    storageBucket: 'tecnigo-6c76c.firebasestorage.app',
    measurementId: 'G-6M4SQ9Y6JM',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNHhvzpZJgCkFqbf91COCLeBFzY3s_djI',
    appId: '1:885029793401:android:ab838b431154d23c1f6ea8',
    messagingSenderId: '885029793401',
    projectId: 'tecnigo-6c76c',
    storageBucket: 'tecnigo-6c76c.firebasestorage.app',
  );
}
